version: '3'
services:
  mongo:
    container_name: mongo1
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/ --quiet
      interval: 10s
      timeout: 10s
      retries: 5
    expose:
      - "27017"
    ports:
      - 27017:27017
    volumes:
      - mongo-data1:/data/db
    restart: on-failure


  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - 127.0.0.1:8081:8081
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_URL=mongodb://root:example@mongo1:27017/
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://localhost:8081 2>&1 | grep Mongo 1>/dev/null || exit 1"]
    restart: "always"

volumes:
  mongo-data1:
